name: hello_world
description: An app built using Flutter for web

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: ^2.1.5
  pedantic: ^1.8.0+1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
